### ISSUE TITLE
The Release .zip appears to be incorrectly formatted 

### ISSUE THREAD

**Issue by DwarfWoot** [lukeadickinson/HollowKnight.NoWalkOfShame#1]
Hey, just wanted to give you a heads up: The release is inside of an extra folder, meaning that when this mod is added via an installer (such as Scarab), it won't actually load for the players.
![image](https://user-images.githubusercontent.com/1775272/202877350-f66decf4-91ee-4742-a380-3b097fae5b7d.png)

**Comment by lukeadickinson** [comment]
Thanks for pointing this out! I have it fixed now.
